# Generated by Django 5.1.7 on 2025-03-21 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen_parte', models.ImageField(upload_to='partes')),
                ('imagen_flashcards', models.ImageField(upload_to='flashcards')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.parte')),
            ],
        ),
    ]
