# Generated by Django 5.1.7 on 2025-03-21 22:44

import flashcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='imagen_flashcards',
            field=models.ImageField(upload_to=flashcards.models.parte_flashcard_path),
        ),
        migrations.AlterField(
            model_name='parte',
            name='imagen_parte',
            field=models.ImageField(upload_to=flashcards.models.parte_image_path),
        ),
    ]
